lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  - .github/workflows/nf-test.yml
  - .github/actions/get-shards/action.yml
  - .github/actions/nf-test/action.yml
  - conf/igenomes.config
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
  readme:
  - nextflow_badge
repository_type: pipeline
template:
  prefix: folkehelseinstituttet
  skip:
  - github_badges
  - igenomes
