---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::r-gridextra=2.3
- conda-forge::r-png=0.1_8
- conda-forge::r-seqinr=4.2_36
- conda-forge::r-tidyverse=2.0.0
