---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::r-jsonlite=2.0.0
- conda-forge::r-tidyverse=2.0.0
