# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "instrumentid"
description: Extract the id of the Illumina sequencer
keywords:
  - illumina
  - seqkit
tools:
  - "seqkit":
      description: "A cross-platform and ultrafast toolkit for FASTA/Q file manipulation"
      homepage: "https://bioinf.shenwei.me/seqkit/"
      documentation: "https://bioinf.shenwei.me/seqkit/usage/"
      tool_dev_url: "https://github.com/shenwei356/seqkit"
      doi: "10.1371/journal.pone.0163962"
      licence: ["MIT"]
      identifier: biotools:seqkit

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - reads:
        type: file
        description: FASTQ files produced by an Illumina sequencer
        pattern: "*.{fq,fastq}"
        ontologies:
          - edam: "http://edamontology.org/format_1930" # FASTQ

output:
  id:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.sequencerID.tsv":
          type: file
          description: TSV file with no header and a the sequencer id as the only entry
          pattern: "*.{tsv}"

  versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: "http://edamontology.org/format_3750" # YAML

authors:
  - "@jonbra"
maintainers:
  - "@jonbra"
